import { Category } from "./constants";

export const categories = {
  [Category.personPlaceAnimal]: [
    "Perro",
    "Elefante",
    "París",
    "Familia",
    "Doctor",
    "Escuela",
    "León",
    "Nueva York",
    "Abeja",
    "Bailarina",
    "España",
    "Gato",
    "Casa",
    "Enfermera",
    "Playa",
    "Caballo",
    "Policía",
    "Montaña",
    "Niño",
    "Restaurante",
    "Jirafa",
    "Bombero",
    "Océano",
    "Pirata",
    "Canguro",
    "Payaso",
    "Astronauta",
    "Estadio",
    "Mariposa",
    "Rey",
    "India",
    "Esquimal",
    "Rana",
    "Actor",
    "Bosque",
    "Cocinero",
    "Parque",
    "Sirena",
    "Científico",
    "Desierto",
    "Hada",
    "Profesor",
    "Granja",
    "Zoológico",
    "Estudiante",
    "Circo",
    "Aeropuerto",
    "Tigre",
    "Mago",
    "Espía",
  ],
  [Category.object]: [
    "Libro",
    "Pelota",
    "Teléfono",
    "Reloj",
    "Computadora",
    "Gafas",
    "Cámara",
    "Lámpara",
    "Cepillo",
    "Bolsa",
    "Silla",
    "Llave",
    "Paraguas",
    "Bicicleta",
    "Sombrero",
    "Radio",
    "Cuchillo",
    "Maleta",
    "Camisa",
    "Caja",
    "Piano",
    "Cocina",
    "Espejo",
    "Guitarra",
    "Martillo",
    "Bolígrafo",
    "Botella",
    "Perfume",
    "Carro",
    "Caja de música",
    "Avión",
    "Balón",
    "Microscopio",
    "Pantalones",
    "Lápiz",
    "Cafetera",
    "Cuaderno",
    "Juguete",
    "Heladera",
    "Escoba",
    "Telescopio",
    "Cepillo de dientes",
    "Vaso",
    "Escalera",
    "Horno",
    "Caja de herramientas",
    "Auriculares",
    "Escultura",
    "Batería",
    "Perchero",
  ],
  [Category.action]: [
    "Correr",
    "Saltar",
    "Nadar",
    "Leer",
    "Bailar",
    "Cantar",
    "Dormir",
    "Comer",
    "Beber",
    "Escribir",
    "Dibujar",
    "Jugar",
    "Estudiar",
    "Trabajar",
    "Cocinar",
    "Llamar",
    "Caminar",
    "Reír",
    "Llorar",
    "Soñar",
    "Saltar la cuerda",
    "Montar en bicicleta",
    "Hacer ejercicio",
    "Navegar",
    "Esquiar",
    "Pintar",
    "Conducir",
    "Volar",
    "Cortar",
    "Lavar",
    "Barrer",
    "Llamar por teléfono",
    "Enviar mensajes",
    "Tomar fotos",
    "Jugar al fútbol",
    "Hacer yoga",
    "Jugar videojuegos",
    "Bucear",
    "Hacer senderismo",
    "Jugar al tenis",
    "Tomar un baño",
    "Pescar",
    "Cazar",
    "Hacer malabares",
    "Hacer piruetas",
    "Hacer acrobacias",
    "Cantar karaoke",
    "Hacer magia",
  ],
  [Category.difficult]: [
    "transatlántico",
    "expresión",
    "margarina",
    "cresta",
    "amerizaje",
    "alfalfa",
    "registro",
    "cachorro",
  ],
  [Category.allPlay]: [
    "Fiesta",
    "Risa",
    "Abrazo",
    "Regalo",
    "Amor",
    "Alegría",
    "Tristeza",
    "Sorpresa",
    "Miedo",
    "Enojo",
    "Esperanza",
    "Libertad",
    "Amistad",
    "Tiempo",
    "Memoria",
    "Sueño",
    "Espacio",
    "Música",
    "Arte",
    "Diversión",
    "Aventura",
    "Reto",
    "Desafío",
    "Magia",
    "Emoción",
    "Relajación",
    "Paz",
    "Éxito",
    "Creatividad",
    "Energía",
    "Equilibrio",
    "Silencio",
    "Sonrisa",
    "Sonido",
    "Imaginación",
    "Fantasía",
    "Felicidad",
    "Fuerza",
    "Paciencia",
    "Pensamiento",
    "Poder",
    "Ritmo",
    "Sensación",
    "Sensibilidad",
    "Serenidad",
    "Sueño",
    "Ternura",
    "Vida",
    "Voluntad",
    "Aire",
    "Agua",
    "Fuego",
  ],
};
